### ISSUE TITLE
Vitejs (build tool) incompatibility (polyfill issue)

### ISSUE THREAD

**Issue by leakim34** [reach-sh/reach-lang#1316]
**Describe the error**

Vitejs cannot be used with reach stdlib, since it uses some node built in modules that are not polyfilled.
You'll start having multiple errors on each built in module used by reach-sh/stdlib.
Starting with one of them below:

```
DependencyNotFoundError
Could not find dependency: 'http2' relative to '/node_modules/@reach-sh/stdlib/dist/esm/rpc_server.js'
```
It will do this for each built in modules used by reach. 

**To Reproduce**

Setup a new environment with vite js using any framework you want (svelte/vue/react/..) and install reach stdlib dep.

```
npm create vite@latest my-vue-app -- --template vue
npm i @reach-sh/stdlib url-parse readline
npm run dev 
```
Import reach-sh/stdlib and instantiate it.

```
import { loadStdlib } from "@reach-sh/stdlib";
import MyAlgoConnect from "@reach-sh/stdlib/ALGO_MyAlgoConnect";
const reach = loadStdlib(process.env);
```
OR 

[Codesandbox test](https://codesandbox.io/s/nifty-wind-bcyv4t)

**Expected behavior**

Being able to instantiate the Stdlib and use reach on vitejs. 
Many libraries/frameworks are using vitejs lately for its speed and ease of use instead of the heavy webpack solution.

**Extra information**

It would help and bring many developers that use vitejs lately, it's easy to setup & run in few seconds ! 
Vitejs does not plan to polyfill this in the future since it will decrease their performance and seems to be better way to handle built in module nowadays.

**Comment by CryptoRUSHGav** [comment]
I second this request. Vite is getting harder to bypass and several frameworks (VueJS, Svelte come to mind) have started to bundle it as default.

**Comment by jeapostrophe** [comment]
We will work on this.

I am totally ignorant about these things, so if either of you know, please help.

My assumption #1: People that use Vite know that it is "weird" with respect to dependencies, because it changes when and where things are used.

My assumption #2: Given that, they are used to "configuring Vite to deal with it". I put that in quotes, because I have no idea how that is actually done.

I am working with analogical-thinking that Vite is like Webpack and you need to manually rewrite things --- https://github.com/reach-sh/reach-lang/blob/master/js/stdlib/webpack.config.js

Is that correct? If so, does that mean that we/Reach tell you/leakim34 what to change in your Vite configuration?

Or is there some other way we "be compatible with Vite"? Like, maybe we put in a `vite.config.js` and it says "Do this to `http2`"?

Please help!

**Comment by CryptoRUSHGav** [comment]
@jeapostrophe my knowledge of Vite is purely circumstantial (due to my wish to use VueJS 3 and Vite being bundled with v3 by default) and I make no claim to pretend I even remotely understand Vite.

Unlike Webpack which bundles all your dependencies, Vite tries to create browser-native ES modules and load these modules on a per-request basis. 
I'm unsure how it ends up making our lives miserable but the bottom line is Reach stdlib makes use of crypto and buffer dependencies in a way that the usual "fixed" browser-bound packages we include and specify in the config (such as crypto and buffer) are throwing exceptions.

The simplest approach would be to start a Vue 3 standard project, include @reach-sh/stdlib, and try to get the project to build.

**Comment by jeapostrophe** [comment]
Thank you for the advice! Follow this issue for the solution

**Comment by mannyyang** [comment]
@jeapostrophe looking forward to your solution

**Comment by Gungy2** [comment]
Just this line: `import { loadStdlib } from '@reach-sh/stdlib'` is impossible to run in a vite build. Then stdlib makes use of Express, which in turn makes of http, that needs `http.ServerResponse` which is not mocked by _any_ node polyfills. Can someone clarify why a client library uses Express and other Node APIs (such as `fs` )? For example, I do not see the point of the file `rpc_server.ts` to be in the client library.

Thank you!
