### ISSUE TITLE
Encountering race condition in tutorial 9 - Web Interaction

### ISSUE THREAD

**Issue by lmedury** [reach-sh/reach-lang#134]
In [tutorial 9](https://docs.reach.sh/tut-9.html), the contract information is rendered after deploying the contract as Alice. Before I attach to the contract as Bob, the following unhandled exception shows up:

![frontend-error](https://user-images.githubusercontent.com/44927331/117734114-680f8300-b210-11eb-9877-6d64c98b00ac.png)

Steps to reproduce:

1. Follow the [tutorial](https://docs.reach.sh/tut-9.html) from start to end.

To open the react application: 
```
2. ./reach react 
```
3. In the frontend, click on Deployer -> Set Wager ->  Deploy -> Choose Ropsten Network in Metamask -> Submit. At this point, I got the unhandled exception. 

This happens when using the Ropsten test network, but works fine when using Ganache.

**Comment by DanBurton** [comment]
I'll take a look

**Comment by DanBurton** [comment]
I'm able to reproduce the error... nondeterministically. The workaround for users is just to refresh the page and try again. But I'll see what I can do to address the issue.

**Comment by DanBurton** [comment]
Thanks for the report. I've made it so that if the error occurs, it will have a more descriptive error message. But I've also added some better retry logic around this particular error, which should be sufficient to prevent it from surfacing to users. Feel free to reopen if you find this is insufficient.
