### ISSUE TITLE
Reach seems to produce impossible values for counter-example to failed "check" statement

### ISSUE THREAD

**Issue by imfeelingitchy** [reach-sh/reach-lang#1468]

**Comment by jeapostrophe** [comment]
I can see the original post in my email, so I want to give you a little bit of advice.

The ONLY thing that Reach can track about the variables in a `parallelReduce` are those things in the invariant. Your invariant is
```
    .invariant(balance() == 0 && balance(tok) == sumOfHowMany * decimalFactor)
```
But the variables are
```
  const [howMany, sumOfHowMany, evenSum, oddSum, deadlineBlock, keepGoing]
```
This means that you know absolutely nothing about `howMany`, `evenSum`, `oddSum`, `deadlineBlock`, and `keepGoing`. Even `sumOfHowMany` is almost totally unconstrained because `x = y * z` doesn't really constrain `y` when `x` and `z` are free.

I think that you need to add an invariant that says something like
```
.invariant(sumOfHowMany == evenSum + oddSum)
```

There is also a relationship between `howMany` and `sumOfHowMany`:
- When `howMany` is 10, then `sumOfHowMany` is 10 + 9 + 8 + 7 + 6 + 5 + 4 + 3 + 2 + 1 + 0
- That's sort of like the "additive" factorial.
- That's called a triangle number, or binomial coefficient
- So, you really have the invariant:
```
.invariant(sumOfHowMany == howMany * (howMany + 1) / 2
```

I recommend that you read the guides about verification:
- https://docs.reach.sh/guide/assert/
- https://docs.reach.sh/guide/loop-invs/

In particular, this sentence from the first is relevant: "At a high-level, the goal of a programmer getting started with verification is to write down every single assumption they have into the program". You have assumptions about the relationships of these four variables that you have not written down yet.
