### ISSUE TITLE
Inquiry on adding support for apple silicon

### ISSUE THREAD

**Issue by aorumbayev** [reach-sh/reach-lang#177]
## Issue description

I followed basic steps in https://docs.reach.sh/tut-2.html after running `reach run` I get the following set of logs:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
make: *** [build/index.main.mjs] Error 137
```

## Hardware info

OS Version : macOS Big Sur 11.4
Chip: Apple M1

## Further notes

Would appreciate any feedback input on this, I suspect it has something to do with the M1 chip itself, running identical set of steps on an intel based Mac works without any issues. Thanks in advance for any replies!

**Comment by MrJackdaw** [comment]
Hello! Thought I might jump in and help. I'm also on a mac

Are you using the latest version of the `@reach-sh/stdlib` library? Current version (at time of writing) is `0.1.2-rc.56`.

**Comment by aorumbayev** [comment]
@MrJackdaw yes i believe I run the update command via reach cli. I assume it pulled the latest version as of now.

**Comment by aorumbayev** [comment]
@MrJackdaw I also tried setting the experimental big sur virtualisation in docker settings, didn't do a trick for me unfortunately.

**Comment by jeapostrophe** [comment]
Right now, we don't support Apple Silicon. This is because we use packages X, Y, and Z, and they don't support it. It *might* be possible to use emulation and the existing x86 version --- https://docs.docker.com/docker-for-mac/apple-silicon/

If you'd like we can leave this issue open for you to track when we support it, but be assured, we'll make a big deal about it when we support the new Macs :)

**Comment by aorumbayev** [comment]
Thank you for the update @jeapostrophe ! Yes, please keep the issue open, would love to track the progress. 

Reach has amazing potential, so the more platforms + frontend clients you'll eventually support, the more people will contribute and make codebase more mature. I also personally think if you guys could add a python frontend client (instead of current RPC option), that would be a great boost for projects in the ecosystem, I think a lot of people rely on python based algo sdks and pyteal, so giving a native client for python backends for reach would be amazing.

Keep up the great work, and thank you ! :-)

**Comment by AwolDes** [comment]
Hey @jeapostrophe just checking in on this - with the recent updates to Reach has anything changed? Is there a particular dependency that is blocking Reach working on apple silicon devices?

**Comment by jeapostrophe** [comment]
Right now, we're waiting/working on Haskell Stack support --- https://github.com/commercialhaskell/stack

**Comment by phoniks** [comment]
@jeapostrophe I've been able to get stack compiled on my M1 Macbook - should it theoretically be possible to build my own images from the dockerfiles and run Reach?

**Comment by jeapostrophe** [comment]
Yes, essentially you want to go to the `hs` directory and type `hs-build`

**Comment by phoniks** [comment]
Cool, that worked.  Is there a contributors guide or something like that that might help me get it configured correctly?  I got an error: `Unset `REACH_EX` environment variable`, but I'm not sure how to set it.

**Comment by phoniks** [comment]
As you expected once the REACH_DOCKER variable was set to 0 things worked perfectly without any additional steps. Thanks @jeapostrophe.

**Comment by phoniks** [comment]
@jeapostrophe - I've got reach running on my M1, and I'd be interested in submitting a PR to resolve this issue, but I'm not sure where to begin.  If I understand correctly, it's an issue of Haskell Stack not being officially available yet but since I have it working on my machine would it just be a matter of including the new M1 compatible docker images?

**Comment by jeapostrophe** [comment]
Thanks @phoniks

We know that you can install `stack` and then go into `hs` and run `make hs-build` and get a working version of Reach.

The issue is that we don't distribute Reach as platform-specific binaries built this way, nor do we expect users to compile it themselves. Instead, we distribute Reach via Docker. Specifically the Dockerfiles here --- https://github.com/reach-sh/reach-lang/blob/master/hs/Dockerfile.haskell-build-artifacts --- https://github.com/reach-sh/reach-lang/blob/master/hs/Dockerfile.reachc --- https://github.com/reach-sh/reach-lang/blob/master/hs/Dockerfile.reach-cli --- are used to build images that the reach script --- https://github.com/reach-sh/reach-lang/blob/master/reach --- uses to invoke the compiler.

This Docker-based set up is so that users don't need to manage any dependencies (other than Docker.) The problem is that the main Dockerfile --- https://github.com/reach-sh/reach-lang/blob/master/hs/Dockerfile.haskell-build-artifacts --- is based on Alpine Linux and Stack (the Haskell build tool) does not yet support Alpine on any platform other than X86-64 --- https://github.com/commercialhaskell/stack/blob/255cd830627870cdef34b5e54d670ef07882523e/etc/scripts/get-stack.sh#L327 --- in fact, they don't support anything but X86-64.

Stack only works on M1s, because the CPU translation system (Rosetta 2?) is running using the X86-64 binary, but that's not possible on Linux or (I believe) with Docker. Once you've got Stack running, then GHC (the Haskell compiler) can effectively build an AARCH64 version of Reach.

**Comment by tuomohopia** [comment]
@phoniks & @jeapostrophe would either one of you be able to give a bit more detailed instructions on how to compile Reach successfully on Mac M1 with Haskell Stack?

For me, I get the following error when having `haskell-stack` installed via `brew` and attempting to run `make hs-build` in the `hs/` folder:
```sh
I don't know how to install GHC for (OSX,AArch64), please install manually
make: *** [hs-build] Error 1
```

I suppose it's because `lts-17.4` would use [ghc-8.10.4](https://www.stackage.org/lts-17.4) compiler which is [unsupported](https://github.com/commercialhaskell/stack/issues/5617#issuecomment-915483014) for M1 right now?
https://github.com/reach-sh/reach-lang/blob/745d69352724984b4719c05359fe0c1e8c93fb77/hs/stack.yaml#L1

Did you manually override the `lts` compiler version somehow and forced the compilation on one of the supported GHC versions?

**Comment by jeapostrophe** [comment]
We (Reach) don't support this path, but are working on it. I don't know why the error you're seeing shows up.

**Comment by phoniks** [comment]
I think the key is to use [Rosetta](https://osxdaily.com/2020/12/04/how-install-rosetta-2-apple-silicon-mac/).   When tying to help someone else set this up we did run into this problem - I'm not sure if she ever overcame it, but when I did this process I never ran into that error.  My thinking at this point is that you should just switch to an i386 terminal and run the install process normally.  I'd love to hear if that works for you because even if it's not supported yet it would be great to come up with a repeatable set of steps that people can use to set up Reach on their M1s.

For reference this is the version of Haskell Stack that's installed and working with Reach on my M1:
`Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4`

**Comment by DanBurton** [comment]
I'm pleased to say that we now support using reach on m1 machines!

Docker makes it a little trickier than simply using Rosetta, unfortunately.
Gladly, we were able to develop a release process that leverages docker manifests in order to support `arm64`.

You can take a look at our images on docker hub and notice that two architectures are now listed under each newly-released tag:

https://hub.docker.com/r/reachsh/reach/tags?name=2021-12-10
