### ISSUE TITLE
Compiler error:   continue not in while

### ISSUE THREAD

**Issue by mrweiner** [reach-sh/reach-lang#220]
The program is in a fairly finished state so I'd rather keep it private. I'll pass the source along to Jay.

**Comment by jeapostrophe** [comment]
Good news: I found a really small example program with the same problem.
Bad news: Your program can't work and the compiler change I'm working on is all about detecting the problem and showing it well.

Your `parallelReduce` inside of a `while` violates the "`continue` must be dominated by communication" rule, because the `which` behind the scenes of the `parallelReduce` could have a false condition and thus the `continue` will immediately run. You can compare the `pr220.rsh` programs in the commit --- https://github.com/reach-sh/reach-lang/commit/10e273b034e656e72ee3b40b95e672146b76cc87

Now, it may not actually be the case that that is possible in your program, in which case this is an example of conservativism of Reach. I couldn't tell by looking at your program, so I haven't pushed too hard on that avenue.

**Comment by mrweiner** [comment]
Thanks @jeapostrophe, makes sense. Do you think it might be worthwhile for me to to deconstruct my `parallelReduce` implementations to `while`+`fork` instead to try and figure out where it's breaking down? If I go that route, do you think I should wait until you get your compiler update released?

**Comment by mrweiner** [comment]
It actually looks like just adding a `commit(); Anybody.publish();` before one of my `continues` fixes the problem, so nevermind!
