### ISSUE TITLE
RE0073 on match statement.

### ISSUE THREAD

**Issue by hernandp** [reach-sh/reach-lang#246]
The following experimental program will throw 

 ```
reachc: error[RE0073]: Switch contains duplicate case, deposit at ./index.rsh:74:60:case; first defined at ./index.rsh:74:60:case
```

when deciding for a variant **or** default, in a publish expression of a Parallel Reduce loop.

It is a bug or something I missed?
Version is latest reach at this time of writing.
Thank you.

```

'reach 0.1';
'use strict';

//
// Command is a variant-type (Data) containing the
// available commands to execute
//
const Command = Data({
  deposit: Tuple(UInt, Token)
})

//
// Interaction interfaces
//
const ICommon = {

  // Get command from front-end
  getCommand: Fun([], Command)
}

const IUser = {
  ...ICommon
}

const AppParams = Object({
  randDCTokenAddress: Token
})

const IGovernor = {
  ...ICommon,
  getParams: Fun([], AppParams)
}


// 
// Evaluates publish-expression and returns proper object
// if command matches.
//
const EvalCommand = (what) => {

}

export const main = Reach.App(
  {
    deployMode: 'constructor',
    verifyArithmetic: true  // This should be disabled in production
  },
  [
    ParticipantClass('User', IUser),
    Participant('Governor', IGovernor)
  ], (User, Governor) => {

    // Require governor to set some parameters
    //
    Governor.only(() => {
      const randDCToken = declassify(interact.getParams()).randDCTokenAddress;
    });
    Governor.publish(randDCToken)

    const [running] =
      parallelReduce([true])
        .invariant(balance() == 0)
        .while(running)
        .case(
          User,
          (() => ({
            when: (declassify(interact.getCommand())).match({
              deposit: () => { true },
              default: (x) => { false }
            }),
            msg: cmd
          })
          ),
          ((msg) => ([msg[0], msg[1]]),  // Token and amount.
            ((msg) => {
              transfer(1, randDCToken).to(User);
              commit();
            })))
        .timeout(false)
  }
);
```

**Comment by jeapostrophe** [comment]
Thanks @hernandp for finding this. This is definitely a problem in Reach because either there's an error or it's a bad error message. In your case, you can make progress by removing in the `default` case, since you have everything covered, since there's only one variant.

@chrisnevers Will you look at this? The problem is here --- https://github.com/reach-sh/reach-lang/blob/master/hs/src/Reach/Eval/Core.hs#L2644 --- we are going through the keys of the match object in ascending order, but I think we should special case and also put the `default` case last so it will play nicer with the switch errors in the macro output; before you do that you should change the annotations --- https://github.com/reach-sh/reach-lang/blob/master/hs/src/Reach/Eval/Core.hs#L2630 --- based on the `sss_at` of the case (include it in args_x_case)

**Comment by hernandp** [comment]
Thanks @jeapostrophe.  Leaving just one case will throw (-- i dont know if the context of the error is in the `match` statement or due to other problems, just FYI):

```
reachc: error[RE0000]: Invalid function application. Expected 0 args, got 1 for function defined at ./index.rsh:75:27:function exp
```

btw Can a particular variant-type member be tested without `match` ? e.g, let the `Command`  variant:
```
const Command = Data({
  deposit: Tuple(UInt, Token),
  borrow: Tuple(UInt, Token),
  withdraw: Tuple(UInt,Token)
})
```

so It would be possible to do:

```
cmd.isSome(deposit)
```

Probably this could be implemented as a function using `match` of course.

Thanks.

**Comment by jeapostrophe** [comment]
That error, @hernandp, is because this line `deposit: () => { true },` is not `deposit: (_) => { true },` (notice the parameter) and the `deposit` case contains a Tuple.

`isSome(x)` only detects if `x` is a `Some` instance. I think you could guess the implementation: https://github.com/reach-sh/reach-lang/blob/master/hs/rsh/stdlib.rsh#L41-L43

You may want to write some functions like that and maybe we could figure out a succinct way to make a bunch of them for users.
