### ISSUE TITLE
Once JS RPC debugging starts, it can not be turned off .

### ISSUE THREAD

**Issue by rfustino** [reach-sh/reach-lang#261]
When using REACH_DEBUG environment variable for RPC JS debugging... 

export REACH_DEBUG=0    // RPC debugging
export REACH_DEBUG=1    // RPC and line by line debugging
export REACH_DEBUG=     or unset REACH_DEBUG    //turns off debugging

The exception is in RPC JS, there is a bug, that once RPC debugging starts, it can not be turned off even when unset. 
Again this is just for RPC JS, .... RPC Python and RPC Go works as expected and unset

**Comment by jeapostrophe** [comment]
What's the difference between "RPC debugging" and "line-by-line debugging"? Here's my hypothesis: the first is the messages that say `RPC m` and `RPC m -> r`, but the second is the diarrhea messages about everything Reach is doing.

If so, then I suspect the problem is that this comparison --- https://github.com/reach-sh/reach-lang/blob/master/rpc-client/js/index.mjs#L32 --- is not this comparison --- https://github.com/reach-sh/reach-lang/blob/master/js/stdlib/ts/shared_impl.ts#L321-L326

**Comment by jeapostrophe** [comment]
If I'm wrong about what I think the problem is, please reopen!

**Comment by jeapostrophe** [comment]
(This won't be included until the 0.1.4 release)

**Comment by jeapostrophe** [comment]
@rfustino You didn't re-open, you made a new issue. What is wrong with my diagnosis of the problem?

**Comment by rfustino** [comment]
ok. actually I miss-read your reply. I missed the 'If' on 'If' I'm wrong.  So I re-opened it. Have not re-opened an issue before, i thought that was how it was done Sorry :) my bad. Will close out the other one.

**Comment by jeapostrophe** [comment]
Oh, okay. So it sounds like you think the problem might be solved (but of course you can't test it yet)
