### ISSUE TITLE
Wrapper for Magic Wallet Integration - Feature Request

### ISSUE THREAD

**Issue by kodisj** [reach-sh/reach-lang#274]
All, I am trying to integrate Magic ( https://magic.link/docs/blockchains/algorand ) with Reach, looks like it needs a wrapper with ARC 11 compatibility.

**Comment by jeapostrophe** [comment]
We do not plan on implementing any new ARC-11 wrappers. We only have the one for MyAlgoConnect, because we need to have something available until wallets start adding ARC-11 support themselves. If you want to do it yourself, you'll want to refer to 
- https://github.com/reach-sh/ARCs/blob/reach-wallet/ARCs/arc-0011.md
- https://github.com/reach-sh/reach-lang/blob/master/js/stdlib/ts/ALGO.ts#L587-L685

I think it should be quite doable based on the way the MyAlgoWallet fallback already works. You may need a module like
- https://github.com/reach-sh/reach-lang/blob/master/js/stdlib/ts/ALGO_MyAlgoConnect.ts
to deal with browser/node compatibility.
