### ISSUE TITLE
11 Issues that I encountered

### ISSUE THREAD

**Issue by kodisj** [reach-sh/reach-lang#421]
REACH ISSUES:
1)	Minting token using REACH does not show in AlgoExplorer when we search for the asset using ASA number.  It only shows in the balance of the asset holder.  REACH claims that the data (MetaData) is perfect on chain, so it is an AlgoExplorer issue.
2)	Minting token using REACH does not show Asset Name and Unit in GoalSeeker when we search for the asset using ASA number.  REACH claims that the data (MetaData) is perfect on chain, so it is a PureStake issue.
3)	Normal import of MyAlgo_WalletConnect lib from REACH stdlib does not work
4)	Normal import of WalletConnect (Algorand WalletConnect) lib from REACH stdlib does not work.  We tweaked the stdlib library to use named import instead of default import, then it worked, i.e, instead of import ethers from ethers, import {ethers} from ethers.
5)	REACH does not give correct value in BalanceOf(acct,token).  It shows 0 or Algo balance
6)	REACH is giving us 500 error in mainNet  when it did not get the network time and later it got fixed with retry loop.
7)	REACH’s group transaction with inner transactions does not show in escrow account in AlgoExplorer
8)	REACH’s group transaction with inner transactions does not show the algos coming into the account.
9)	REACH program crashes if the participant balance is low and could not give min balance to escrow.
10)	REACH has bug in stdlib.transfer() function, it expects account of the receiver instead of address.
11)	REACH contract initiated signing pop-up is blocked by the browser even if the pop-up is allowed by the user.

**Comment by jeapostrophe** [comment]
1. As you note, AlgoExplorer has identified this as an error on their end.
2. As you note, this is a problem with PureStake.
3. How are you building your application? If you are using webpack directly, you may need to configure it to identify which modules you want to use. This is not a Reach problem, but an issue with your JS build system.
4. Same as 3
5. Thank you for identifying this problem last week. We've done two releases that have the fix for this. Please update and let us know if you still have the problem.
6. I'm glad this issue was fixed for you.
7. This is an AlgoExplorer problem: they are not showing what actually happens on-chain.
8. This is an AlgoExplorer problem: they are not showing what actually happens on-chain.
9. You can only run a program that requires a user to have 10 ALGOs if the user actually has 10 ALGOs.
10. You reported this issue recently and we've done two releases that have it fixed. Can you update and let me know if you still have the problem?
11. You should consult with the browser and MyAlgoConnect to see why MAC is using a pop-up style that the browser is rejecting.
