### ISSUE TITLE
Feature Request: hard coding addresses

### ISSUE THREAD

**Issue by AwolDes** [reach-sh/reach-lang#434]
:wave: hey there. Right now, the only way to hard code an address is the following. If I have missed another way, please point me in the right direction of the docs!

1) A Participant publishes a value from the frontend
```javascript
//
const participantInteract = {
    getAddr: Fun([], Address)
}

Participant.only(() => {
    // getAddr returns an address from the frontend
    const addr = interact.getAddr();
}
Participant.publish(addr);
```
2) Set a variable to `this` in an interaction, and publish
```javascript
Participant.only(() => {
    const addr = this;
}
Participant.publish(addr);
```

It would be very helpful for our project if we could do something like this to hard code addresses for a contract.
```javascript
const addr = new Address('0xVet...')
```

The use case is for paying out fees in our case.

**Comment by AmbroseHill** [comment]
A third helpful use case is for having null or zero addresses. Currently using maybe types to get around this but it would be helpful to set default addresses or have a null value address that indicates this address is currently unusable.  The use case is token staking and storing users addresses in a global array. 

```js
const nullAddress = new Address(0x000....) 

if (User withdraws stake / leaves protocol) {
    userArray[userAddress] == nullAddress
}

// Later in the logic when distributing rewards to staked users
if addr != nullADDRESS {
    // Pay out rewards
}
```

**Comment by MetaB0y** [comment]
I also want to have this feature, and a similar thing for `Token`. Something like
```
const token = new Token(asaId)
```

**Comment by jeapostrophe** [comment]
If you hard-code an address or a token, then your program is un-testable, because the addresses on e.g. MainNet are not going to be the same as the addresses on TestNet, so you'll need to have different versions of your program text for each of them. For example, in Algorand, USDC is 31566704 on MainNet and (I believe) 10458941 on TestNet; while in Ethereum it is 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48 on main net and (I believe) 0xfe724a829fdf12f7012365db98730eee33742ea2 on Ropsten.

The alternative, of having your deployer set the address is testable and is equivalent in almost every way from an implementation perspective, because the address/token identity is fixed from the beginning of the program and if it is not part of a loop, then it cannot be updated.

What do you think of this perspective?

--

On the specific instance of `NULL`, have you every watched Tony Hoare, the creator of the `NULL` pointer, discuss his thoughts about its legacy and consequences? https://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare/

Obviously this is a giant topic, here are few articles about the pros & cons of `NULL`:
- https://www.nickknowlson.com/blog/2013/04/16/why-maybe-is-better-than-null/
- https://www.ppl-lang.dev/blog/null-safety-vs-maybe-option/index.html

In the specific case of a `NULL` address, a unique failure mode is that it is impossible to send it tokens on a network like Algorand, because (presumably) there is no secret key where the public counter-part is all-zeros. This is a classic example of while `NULL` is dangerous, because it is not an actual object (e.g. address) that can handle the same operations as real objects.

**Comment by AwolDes** [comment]
@jeapostrophe you make a good point, however doesn't that kind of decision get made by the team building Reach? Sure it may introduce extra complexity **but that would be the teams choice**, Reach would simply allow them to make that decision.

It would be bad if a frontend could pass any ASA token id to the contract, without being able to validate that token is allowed to be used. To illustrate the point, I'll use a lending protocol as an example. This protocol must be able to whitelist assets that have been voted in via governance, or that meet a certain criteria (like passing KYC checks or something). Someone could fork the code & add new collateral, but it would not effect the deployed application.

Currently my understanding is that a malicious frontend could interact with the contract & pass a collateral type that is not meant to be supported.

**Comment by jeapostrophe** [comment]
At a high-level, I agree with you that we should allow Reach users to make their own decisions. However, in general, Reach is about identifying things that can never work and disallowing them statically. (For example, you never want an arithmetic overflow on chain.) There are ways in which we are currently incomplete (but sound) so we reject things that could actually be okay in practice. (For example, dynamic token passing patterns.) We have ideas of how to improve this and get closer to completeness, but aren't there yet.

NULL addresses, in my opinion, are an example of something that can never work, because they are not real addresses. I want to interpret your request for NULL addresses as saying "Maybe is too hard to work with and I want something nicer and more ergonomic." As an analogy, if a function `f` normally returns a number, but might error, the type could be `f : A -> Maybe Number`, but that might be really annoying. In languages like C, that's what we have to do, or we have to say "It will return 42 when it errors". But in languages like Java, then we can throw an exception. So, exceptions can be a "more ergonomic" way to deal with partial functions.

As far as the issue of malicious frontends, embedding addresses and token identifiers would not provide any security over the alternative. Suppose you had

```
const Deployer = Participant('Deployer', { ... });
const USDC = ALGO.Token(31566704); // making up syntax for doing this
deploy();
Deployer.publish();
```

then the way you'd do that today is

```
const Deployer = Participant('Deployer', { USDC: Token });
deploy();
Deployer.only(() => { const USDC = declassify(Deployer.USDC); });
Deployer.publish(USDC);
```

What's the difference between these programs? You might think the difference is that in the first one, the USDC token "can't be changed", but that's not true. It is going to be embedded in the program bytecode and the deployer can just find the `31566704` and change it to `42`. The Deployer has just as much power in the first as the second case.

Now, if they change it and deploy it as app 42, then if another client tries to attach to 42, they'll see the bytecode is different during contract verification and reject it. So, that's good, but what would happen in the current world? Well, we'd add a line:

```
const Deployer = Participant('Deployer', { USDC: Token });
deploy();
Deployer.only(() => { const USDC = declassify(Deployer.USDC); });
Deployer.publish(USDC);
EveryoneElse.interact.isItUSDC(USDC); // <- added
```

where `isItUSDC = (x) => stdlib.assert(x == 31566704)` on the front-end.

What's the difference between these? In the first case, we reject the program at bytecode verification. In the second case, we reject the program on the first message. (If you wanted to use APIs, then we'd put `USDC` in a View and the first thing an API client does will be `stdlib.assert(await ctc.v.getTok() == 31566704)`.)

Furthermore, I think that in real deployments, you probably will want the "deployer" to be another contract that launches it with the values chosen by the factory/parent, and not actually in the syntax of the original program.

Finally, in your example of the lending protocol with a white-list of assets, I don't think this is a good use-case of hard-coded addresses, because you want them to change overtime based on governance decisions, so you really want the governance program to have e.g. a view that says "Is token A on the white-list?"

I know I am pushing back hard, but I hope you feel it coming from a place of trying to help. If you feel like there's a use of hardcoded addresses that I'm missing, I'd love to jam about what your need is and we can try to think of something I'll claim is better and if I fail, we can add `ALGO.Address(FooBizzle)`.

**Comment by AwolDes** [comment]
> I know I am pushing back hard, but I hope you feel it coming from a place of trying to help.
Absolutely @jeapostrophe - thoughtful disagreement is very productive. 

I don't mind the frontend verifying a contract is connecting to has the right token listed in a view with something like `stdlib.assert(await ctc.v.getTok() == 31566704)`. I originally was thinking of the bytecode solution but this achieves the same end goal.

Could something similar be done if a contract called another contract? For example User deposits tokens into Contract A, which then calls Contract B asking to exchange the token for the token Contract B mints. Contract B should only do this if Contract A is trustworthy, and has paid using the correct token. This is a little abstract to me, specifically on Algorand, because AVM 1.1 updates are not available yet to play around with.

> Furthermore, I think that in real deployments, you probably will want the "deployer" to be another contract that launches it with the values chosen by the factory/parent, and not actually in the syntax of the original program.

Could not agree with this more, it just isn't possible on Algorand at the moment. In the near term it will become possible; just albeit severely limited by the number of applications an address can create.

**Comment by jeapostrophe** [comment]
My proposed 

> > I know I am pushing back hard, but I hope you feel it coming from a place of trying to help.
> > Absolutely @jeapostrophe - thoughtful disagreement is very productive.
> 
> I don't mind the frontend verifying a contract is connecting to has the right token listed in a view with something like `stdlib.assert(await ctc.v.getTok() == 31566704)`. I originally was thinking of the bytecode solution but this achieves the same end goal.
> 
> Could something similar be done if a contract called another contract? For example User deposits tokens into Contract A, which then calls Contract B asking to exchange the token for the token Contract B mints. Contract B should only do this if Contract A is trustworthy, and has paid using the correct token. This is a little abstract to me, specifically on Algorand, because AVM 1.1 updates are not available yet to play around with.

This is possible in a contract-to-contract call. Views are part of the external interface and you can call them on other contracts just fine.

If you went with the other method---hardcoding and verifying the bytecode---then you wanted a contract to verify the bytecode of another contract---is technically possible, but very difficult. On Algorand, you obviously can't store the actual code of another contract in your contract (because of the size limit), but you could store a hash of it. Unfortunately, bytecode can be up to 8k, but byte strings on the AVM can only be 4k, so you couldn't even load the bytecode of contract A into contract B to call a hashing function. Presumably they will eventually change this (we have a feature request to them to make it possible for byte strings to store contract code) but we have no idea what it will really be like.

> > Furthermore, I think that in real deployments, you probably will want the "deployer" to be another contract that launches it with the values chosen by the factory/parent, and not actually in the syntax of the original program.
> 
> Could not agree with this more, it just isn't possible on Algorand at the moment. In the near term it will become possible; just albeit severely limited by the number of applications an address can create.

Yes, exactly. We're all waiting for these changes :)

**Comment by AwolDes** [comment]
@jeapostrophe I am happy to close this. Your comments were very helpful in clarifying my understanding.

**Comment by AmbroseHill** [comment]
Thanks for the insight Jay!  Happy for this to be closed as well
