### ISSUE TITLE
Feature Request: Custom notes for Algorand contracts

### ISSUE THREAD

**Issue by AwolDes** [reach-sh/reach-lang#435]
At the moment, Reach appends their own notes to transactions on the Algorand blockchain
![image](https://user-images.githubusercontent.com/9693812/144954652-0f32627a-f0ee-4569-95db-2ea7db5b0527.png)

It would be useful from a product perspective to have a `notes` field to track events on chain, rather than in a centralised service like Amplitude. A program could then collate transactions & generate reports etc.

I understand this is somewhat against the Reach ethos, however it would be useful to those building on Algorand.

**Comment by jeapostrophe** [comment]
It's not out of the question. Help me understand what you mean by "track events on chain" and "collate transactions & generate reports". Imagine that the blockchain were an SQL database and you were programming an auction, you want to do something like:

```
SELECT * FROM Txns WHERE ApplicationId = 42 AND Note = "NewBid"
```

And then look through these txns to do something?

If so, consider how you might do this on Ethereum, my assumption is that you'd be using an `event`, like how ERC-20 uses the `Transfer` event to log transfers for the world. We are working on ARC spec to create the concept of an "event" on Algorand and @chrisnevers is implementing it in this PR --- https://github.com/reach-sh/reach-lang/pull/422

**Comment by AwolDes** [comment]
@jeapostrophe I'm thinking from two perspectives. One being product analytics - at a high level, what are users doing, how often are they doing it, etc. The other is being able to understand what a user has done in the event of a bug report. The SQL sample is effectively what I'd like to do.

Events sounds like a far superior solution, but my guess would be it isn't a near term deliverable for the AVM...

**Comment by jeapostrophe** [comment]
The Event feature will be ready this week or next with support on all Reach connectors, including ALGO. It is plausible that our ARC spec for it won't be accepted and we'll need to revise it, but there's nothing stopping it from being supported on the network immediately.

If you're happy with that, then we can close this. If you're not, then there's more to work out with the Notes. For example, some txns don't actually mention the application id, so the pseudo-SQL is actually way more complicated and if some txns aren't generated by the smart contract, so we'd have to put that in the clients and then make the contract reject txns that don't contain the correct note. Finally, notes are actually used by Reach to ensure that the same txn isn't generated twice, because then it will be rejected by the network. This is a subtlety of Algorand that many people don't notice until they use it at scale.

**Comment by AwolDes** [comment]
@jeapostrophe happy to close in favor of events if that's something that will be implemented in some form in the near future. Is there an AVM update required for this? Or is the ARC more defining a standard for emitting events?

**Comment by jeapostrophe** [comment]
It requires no change to the AVM. The ARC will just be about the standard for encoding the information. Our proposal is that when you want to do `Transfer(address, address, uint64)` you should do a `log` of `sha512_256("Transfer(address, address, uint64)")[0..3] <> address <> address <> uint64`. We don't expect this to be controversial, but we have to write it up and people have to agree on it.
