### ISSUE TITLE
Feature Request: Retrieve events for certain addresses

### ISSUE THREAD

**Issue by AwolDes** [reach-sh/reach-lang#523]
For the events feature, is it possible that a specific address can be filtered for?

I imagine this could be an parameter for `next` or `seek` like this:
```javascript
await ctc.e.log.next({ address: xyz });
await ctc.e.log.seek({ address: xyz, time: t });
```

**Comment by jeapostrophe** [comment]
What does it mean for an event to be from a specific address?

Do you mean that the address is the address of the app? If this, that's part of `ctc` (in your example)

Or do you mean that the address is of the account that made that app call that ultimately let to the event being logged? If this, that information is available on the network, but we don't expose it, because we're making an abstraction that is more general. For instance, there may be a network that allows "daemons" that can generate events without any user interaction. If you want that though, then you could just include `this` in the event in Reach and then filter at the application level.

**Comment by AwolDes** [comment]
@jeapostrophe I do mean for a certain address that triggered an event. We could filter at the application layer, but it's more about the performance of retrieving **all** events, rather than retrieving those triggered by a specific address.

If this is considered an anti-pattern, I'm happy if this is closed.

**Comment by jeapostrophe** [comment]
Ah, let me tell you a secret... you have to receive all the events no matter what. There's not way right now with the indexer API to query for specific logs, so we have to get them all and go through them on your machine anyways

**Comment by AwolDes** [comment]
I was afraid this may be the case :face_exhaling: thank you for confirming.
