### ISSUE TITLE
Feature Request: Asset Opt-in and Application Opt-in in the same txn group

### ISSUE THREAD

**Issue by AwolDes** [reach-sh/reach-lang#571]
On Algorand, currently Reach will opt into an asset in one transaction, then in a follow up transaction the Application is opted into. It would be great to batch these together if possible so users just need one transaction when first opting into an application.

**Comment by jeapostrophe** [comment]
First, the "opt into an asset" transaction that you're seeing is not generated "by" Reach automatically. It is generated by you when you call `tokenAccept`.

Second, figuring out ways of bundling txns together into groups is very very hard and it is not necessarily semantics preserving to take two txns that work okay alone and stick them in a group. In particular, Reach contracts ensure that the application opt-in is by itself. (Of course, we could change that.)

Many times we address feature requests very fast... but this is not going to be one of those times, because I don't have a clue how to do this well. However, it is feasible in the relatively short-term to make it so normal application calls can start with an opt-in, so what you consider the second txn won't happen at all... it will just blend in with the normal e.g. API calls.

**Comment by AwolDes** [comment]
Just after submitting this I had a feeling it might be in the "too hard for value provided" basket - no worries. Sounds like the normal application calls are a good solution :+1:

**Comment by jeapostrophe** [comment]
Closing this because it is too big of issue to figure out how to do with how the standard library works. Since Feb, it can be simulated by making a custom wallet, which is kind of a hack.
