### ISSUE TITLE
remote object interaction issues

### ISSUE THREAD

**Issue by MetaB0y** [reach-sh/reach-lang#812]
I am trying to do some remote calls on ALGO-devnet and they throw some unexpected errors. There are 2 seemingly separate problems. 

Please see a repo with a minimal example demonstrating both problems: https://github.com/MetaB0y/reach-remote-problems

I use the latest reach 0.1.10rc-0 but had it in 0.1.9 too.

**Comment by jeapostrophe** [comment]
I'll get on this. Thanks!

**Comment by jeapostrophe** [comment]
I am about to push a fix to the first issue. I was not able to get the second problem.

Your program does have its own problem, you should apply this patch:
```
diff --git a/index.rsh b/index.rsh
index 719a011..5d861c8 100644
--- a/index.rsh
+++ b/index.rsh
@@ -27,9 +27,9 @@ export const farm = Reach.App(() => {
 
   Creator.publish(stakeToken, rewardToken);
 
-  Creator.interact.deployed();
   commit();
   Creator.pay([[100, rewardToken], [1000, stakeToken]]);
+  Creator.interact.deployed();
 
   const stakeM = new Map(UInt);
   const stake = (p) => fromSome(stakeM[p], 0);
```

The farm isn't actually ready for calls until you've done that payment.

**Comment by MetaB0y** [comment]
Thanks a lot! I think the second issue was related to the patch you mentioned, it is not happening after applying the patch.

Somewhat related note: I see REMOTE_FUN.ALGO was added. It definitely seems like something useful but it is really hard to understand how to use it, an example would be helpful.

**Comment by MetaB0y** [comment]
This works in the example repo but unfortunately, I have exactly the same error in my full project.
```
      "message": "TransactionPool.Remember: transaction L4UEMRZ7FRGUJLG5VJKQWC7VAUPEVPUW7RY7NVAL54QTGPYF4QNQ: logic eval error: itxn_begin without itxn_submit. Details: pc=637, opcodes=load 254\nitxn_field XferAsset\nitxn_begin\n"
```
      
 I will double-check my setup (so far looks ok?) and will try to update the repo to make it reproducable.

**Comment by jeapostrophe** [comment]
Re: `REMOTE_FUN.ALGO` --- I don't know how to give an example without going into great detail on TEAL programming. But basically, sometimes you are going to be calling a function that is going to need more fees and we have to have some way of telling the frontend that. That's what the feature is for.

Re: OptIn --- Yes, there's no way to do that right now and I don't know how to do it gracefully at all, because the application doing the opt-in would need to ensure that its minimum balance went up by the amount that is in the current configuration of application it is opting into. This is definitely future work for Reach.
