### ISSUE TITLE
Division by zero in some remote calls

### ISSUE THREAD

**Issue by MetaB0y** [reach-sh/reach-lang#895]
I have a very strange problem that is probably somehow related to remote contract calls.

I created a minimal example to demonstrate this issue: https://github.com/MetaB0y/reach-remote-problems

The crux is the following
```
        const [aPerLp, bPerLp] = liquidityPoolCtc.getLpPrice();
        if (balance(tokenA) != 0 && balance(tokenB) != 0) {
          const aToEqualB = (balance(tokenB) * aPerLp) / bPerLp;
          const aToPay = aToEqualB < balance(tokenA) ? aToEqualB : balance(tokenA);
          const rv = liquidityPoolCtc.addLiquidity
            .pay([0, [aToPay, tokenA], [0, tokenB], [0, lpToken]])
            .withBill([lpToken])(balance(tokenA));
        }
```

On the last line, I get
```
/home/anonymous/github/reach-remote-problems/node_modules/@reach-sh/stdlib/dist/cjs/shared_impl.js:310
                            fail(new Error("".concat(bl, " errored with ").concat(err)));
                                 ^

Error: addTokens errored with Error: division-by-zero [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-division-by-zero ] (fault="division-by-zero", operation="div", code=NUMERIC_FAULT, version=bignumber/5.6.0)
    at /home/anonymous/github/reach-remote-problems/node_modules/@reach-sh/stdlib/dist/cjs/shared_impl.js:310:34
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 ```
 
 I am not sure what exactly causes this problem, it seems to be a very specific case. For example, if I change first line to
 ```const [aPerLp, bPerLp] = [1, 1]``` everything works fine. Everything also works if I change `aToPay` to `balance(tokenA)` in `.pay` argument even if `aToPay == balance(tokenA)`. Basically almost any random change I tried made the error disappear.
 
 Another thing which I'd like to note is that it doesn't even call a remote contract at all. Even if I pass dummy value as `liquidityPoolCtc` id, I still get the same error, despite `getLpPrice` is supposed to be called before.
 
 I feel like it is somehow related to branching (especially `if` but maybe a ternary operator too). 
 
I have another example that causes the same error (and I think it's the same underlying issue) and also acts weird. I think it is a bit more tricky to create a minimal example with it, so I will try to reproduce it after this issue is closed.

**Comment by jeapostrophe** [comment]
First, I have an idea how to fix this.

Second, the root of the problem is that on ALGO, clients need to simulate the execution of the on-chain code to be able to synthesize things like the Accounts and Assets arrays. That means that your Reach frontend is going to run this program before sending the transaction to the network. However, the frontend can't do that simulation for remote objects, like `liquidityPoolCtc.getLpPrice`. So, currently we do something really dumb and just have a "default" value returned for every type. `bPerLp` is a number, so we pretend it will return `0`. Then, when we're simulating we run `(balance(tokenB) * aPerLp) / bPerLp` and that's a divide by zero.

You could avoid this problem by changing `(balance(tokenB) * aPerLp) / bPerLp` to `(balance(tokenB) * aPerLp) / (bPerLp == 0 ? 1 : bPerLp)` and nothing bad would happen, because in the simulation, you'd get 1 and in the real program you'd get something else. That simulation inaccuracy doesn't change the things we're simulating for (Accounts, etc), so it's okay. As it turns out, you may want that check anyways, because your contract program really will crash if `bPerLp` ends up being `0`.

We could avoid this by doing more analysis and cutting out the parts of your program that don't affect what the simulation is for. It's complicated and we're not good enough yet.

**Comment by jeapostrophe** [comment]
The way to solve this is with the new `simXyz` options on remote calls: https://docs.reach.sh/rsh/consensus/#rsh_remote.ALGO

**Comment by jeapostrophe** [comment]
(Sorry for not updating the thread when we made the new features)
